# Generated by Django 3.0.2 on 2020-02-14 04:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(choices=[('Kanye_West', 'Kanye West'), ('Bruno_Mars', 'Bruno Mars'), ('The_Beatles', 'The Beatles'), ('Alicia_Keys', 'Alicia Keys'), ('Bob_Marley', 'Bob Marley'), ('Lil_Wayne', 'Lil Wayne'), ('Adele', 'Adele'), ('Justin_Bieber', 'Justin Bieber'), ('Britney_Spears', 'Britney Spears'), ('DJ_Khaled', 'DJ Khaled')], max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('lyrics', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a particular song', primary_key=True, serialize=False)),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Song')),
            ],
        ),
    ]
